### PR TITLE
Fix uds listener hanging on accept

### LINKED ISSUE #248: unix sockets don't work since the 0.99.6 release
Expected behaviour:
```sh
loop
connected
loop
```
Actual behaviour:
```sh
loop
```
`server.rs`
```rust
use async_std::prelude::*;
use async_std::os::unix::net::UnixListener;
use async_std::task;

async fn run() {
    let socket = UnixListener::bind("/tmp/test.sock").await.expect("bind");
    let mut incoming = socket.incoming();
    loop {
        println!("loop");
        if let Some(stream) = incoming.next().await {
            println!("connected");
        }
    }
}

fn main() {
    task::block_on(run());
}
```
`client.rs`
```rust
use async_std::task;
use async_std::prelude::*;
use async_std::os::unix::net::UnixStream;

async fn run() {
    let mut socket = UnixStream::connect("/tmp/test.sock").await.expect("connect");
    socket.write_all(b"hello world").await.expect("write");
    socket.flush().await.expect("flush");
}

fn main() {
    task::block_on(run());
}
```

### PR DESCRIPTION
**Pull request by mvucenovic**
UDS listener was hanging because the accept method would return `Poll::Pending` without registering the task to be awoken in the case when underlying unix listener returns a `WouldBlock` that gets converted to `None`. This is a hacky fix for this case.

Should fix #248

### CODE REVIEW

**Comment by skade** [comment]
This would be great chance to cover this with a test case to avoid regressions. @mvucenovic, would you be able to find a case that exhibits the (previously broken) behaviour?

**Comment by mvucenovic** [comment]
@skade Sure thing, I would like to write a bigger integration test that reproduces this issue, as I've mentioned in the #248. I won't be able to do this today, but will try to finish it before the weekend. I've submitted this PR early, because I consider this change a hacky one, so any suggestions how this should be done better are welcome.

**Comment by skade** [comment]
@mvucenovic Perfect :+1: thanks for letting me know!

**Comment by mvucenovic** [comment]
Hey @skade, I've added a test that reproduces the listener hanging forever. For me it fails on the master, but passes on this branch.

Interesting thing, my first version of test was not running in two different threads, but used join macro, to run server and client concurrently, and that version was green on the current master. It looked something like this:
```
     // rest of the code is mostly the same
     task::block_on(async {
         let listener = UnixListener::bind(&socket).await.expect("Socket bind");

         let server = ping_pong_server(listener, iter_cnt);
         let client = ping_pong_client(&socket, iter_cnt);

         async_std::io::timeout(
             Duration::from_secs(5),
             async_std::future::try_join!(server, client),
         ).await
     }).expect("not finished successfully");
```
I'll try to investigate why was that the case, just wanted to mention if somebody has any idea.

**Comment by jD91mZM2** [comment]
Hi, sorry for the notification, I just wanted to say that I needed to use unix sockets and switching to your fork solved it for me, just like that. You're awesome! :)

**Comment by stjepang** [comment]
@mvucenovic If you want to force tasks to be executed on separate threads, you can spawn threads manually with `std::thread::spawn` and then use `async_std::task::block_on` to run futures on those threads.

File: src/os/unix/net/listener.rs [hunk 1]
```diff
@@ -93,18 +93,25 @@ impl UnixListener {
     /// ```
     pub async fn accept(&self) -> io::Result<(UnixStream, SocketAddr)> {
         future::poll_fn(|cx| {
-            let res =
-                futures_core::ready!(self.watcher.poll_read_with(cx, |inner| inner.accept_std()));
+            let res = futures_core::ready!(self.watcher.poll_read_with(cx, |inner| {
+                match inner.accept_std() {
+                    // Converting to `would block` so that the watcher will
+                    // add the waker of this task to a list of readers.
+                    Ok(None) => Err(std::io::ErrorKind::WouldBlock.into()),
```
Comment (stjepang) [inline src/os/unix/net/listener.rs]:
```suggestion
                    Ok(None) => Err(io::ErrorKind::WouldBlock.into()),
```

File: src/os/unix/net/listener.rs [hunk 2]
```diff
@@ -93,18 +93,25 @@ impl UnixListener {
     /// ```
     pub async fn accept(&self) -> io::Result<(UnixStream, SocketAddr)> {
         future::poll_fn(|cx| {
-            let res =
-                futures_core::ready!(self.watcher.poll_read_with(cx, |inner| inner.accept_std()));
+            let res = futures_core::ready!(self.watcher.poll_read_with(cx, |inner| {
+                match inner.accept_std() {
+                    // Converting to `would block` so that the watcher will
```
Comment (stjepang) [inline src/os/unix/net/listener.rs]:
```suggestion
                    // Converting to `WouldBlock` so that the watcher will
```

File: src/os/unix/net/listener.rs [hunk 3]
```diff
@@ -93,18 +93,25 @@ impl UnixListener {
...
             match res? {
-                None => Poll::Pending,
                 Some((io, addr)) => {
                     let mio_stream = mio_uds::UnixStream::from_stream(io)?;
                     let stream = UnixStream {
                         watcher: Watcher::new(mio_stream),
                     };
                     Poll::Ready(Ok((stream, addr)))
                 }
+                // This should never happen since None is converted to WouldBlock
```
Comment (stjepang) [inline src/os/unix/net/listener.rs]:
```suggestion
                // This should never happen since `None` is converted to `WouldBlock`.
```

File: tests/uds.rs [hunk 4]
```diff
@@ -39,3 +44,53 @@ fn into_raw_fd() -> io::Result<()> {
         Ok(())
     })
 }
+
+const PING: &[u8] = b"ping";
+const PONG: &[u8] = b"pong";
+const TEST_TIMEOUT: std::time::Duration = Duration::from_secs(3);
```
Comment (stjepang) [inline tests/uds.rs]:
```suggestion
const TEST_TIMEOUT: Duration = Duration::from_secs(3);
```

**Comment by stjepang** [comment]
@skade @yoshuawuyts It seems Clippy checks are failing in this pull request. Should we make Clippy tests not required to pass in CI?

**Comment by yoshuawuyts** [comment]
@stjepang the failure here was an upstream failure iirc that's now been fixed in actions-rs. Re-running the check should solve it. Clippy currently doesn't fail CI.

Additionally #270 should be landing soon now which means clippy errors should be resolved. This would allow us to then enable https://github.com/actions-rs/clippy-check/issues/2#issuecomment-538670997 once it's implemented (if we so desire).

Anyway, going to restart the CI here which *should* fix the error!

**Comment by mvucenovic** [comment]
Thanks for the review @stjepang, I've updated the PR with your suggestions.
